#!/usr/bin/env sh

if git diff-index --cached --name-only HEAD | grep '^website/' > /dev/null; then
    (cd website && hugo >/dev/null)
    uncommitted=`git status --porcelain --untracked-files=all docs | grep '^.[^ ]' | wc -l`
    if [ $uncommitted -ne 0 ]; then
        echo 'COMMIT FAILED: It looks like you forgot to generate the site!'
        exit 1
    fi
fi
